<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Optimize>true</Optimize>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Fishbrain/*.cs" Exclude="../Fishbrain/Program.cs;../Fishbrain/SelfTests.cs" />
    <Compile Include="../Fishbrain/Neural/*.cs" />
  </ItemGroup>
</Project>
