<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Optimize>true</Optimize>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Fishbrain.CausalRuntime/Fishbrain.CausalRuntime.csproj" />
    <ProjectReference Include="../Fishbrain.CausalDemo/Fishbrain.CausalDemo.csproj" />
    <Compile Include="../Fishbrain.CausalCli/*.cs" />
  </ItemGroup>

</Project>
